### ISSUE TITLE
This does not build on kernel 6.1

### ISSUE THREAD

**Issue by VeganBiker** [AlexanderS/tbsecp3-driver#12]
make -C /lib/modules/`uname -r`/build M=$PWD
make[1]: Entering directory '/usr/src/linux-headers-6.1.0-10-amd64'
  CC [M]  ~/tbsecp3-driver/tbsecp3/tbsecp3-core.o
~/tbsecp3-driver/tbsecp3/tbsecp3-core.c: In function ‘tbsecp3_probe’:
~/tbsecp3-driver/tbsecp3/tbsecp3-core.c:179:12: error: implicit declaration of function ‘pci_set_dma_mask’ [-Werror=implicit-function-declaration]
  179 |         if(pci_set_dma_mask(pdev, DMA_BIT_MASK(64)))
      |            ^~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[2]: *** [/usr/src/linux-headers-6.1.0-10-common/scripts/Makefile.build:255: /~/tbsecp3-driver/tbsecp3/tbsecp3-core.o] Error 1
make[1]: *** [/usr/src/linux-headers-6.1.0-10-common/Makefile:2037: ~/tbsecp3-driver] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.1.0-10-amd64'
make: *** [Makefile:4: default] Error 2
